package sample;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

public class SampleApp {

    /**
     * 対象行の抽出パターン
     */
    private static final Pattern FILTER_PATTERN = Pattern.compile("^\\|([iew]).+");

    public static void main(String[] args) throws IOException {

        // 読み込み
        var asciidocLines = Files.readAllLines(Paths.get("./sample-docs/sample-message-list.adoc"),
                StandardCharsets.UTF_8);

        // 変換
        Properties prop = new Properties();
        asciidocLines.stream()
                .map(FILTER_PATTERN::matcher)
                .filter(Matcher::find)
                .map(x -> x.group(0)).forEach(x -> {
            String[] row = x.trim().split("\\|");
            prop.put(row[1], row[2]);
        });

        // 書き込み
        var output = Paths.get("./generated/messages.properties");
        if (!Files.exists(output.getParent())) {
            Files.createDirectories(output.getParent());
        }
        try (var fos = Files.newOutputStream(output)) {
            prop.store(fos, " Generated by sample-asciidoc-2-javaproperties");
        }

    }
}

